### ISSUE TITLE
Manga not showing

### ISSUE THREAD

**Issue by niconico2023** [kafkaien42/guyamoe#10]
I created the media file as instructed, but the manga doesn't show up when I run the server 

![image](https://user-images.githubusercontent.com/130686073/232094015-1d60810d-2ba8-48fe-872d-2a0c9813140b.png)
![image](https://user-images.githubusercontent.com/130686073/232094275-5cda5c22-2ac8-4e2c-b3c8-78408cf58a70.png)
![image](https://user-images.githubusercontent.com/130686073/232094898-c8dde869-d50f-41b0-b65d-1410dd97a861.png)

**Comment by PhiBabin** [comment]
You need upload the manga/chapter thru the web interface. Otherwise, the website's database doesn't know that the series exists.

**Comment by kafkaien42** [comment]
Creating the files in the folder will not make the website see them. You need to create a manga and upload a chapter thru the web interface. Otherwise, the manga is not in the website's database.
