### ISSUE TITLE
Image often fail to load

### ISSUE THREAD

**Issue by bokunodev** [kafkaien42/guyamoe#8]
Hi, while reading manga, the image often fail to load with error `522 connection timeout`.
After going trough the code, i noticed, the part that handle image resizing and blur etc. And the caching mechanism are not concurent safe.
I think, i know how to improve it.

The discord link is dead and thr twitter account is suspended.
So, i decided to make a github issue.

**Comment by kafkaien42** [comment]
`522 connection timeout` is probably caused by our slow server. Also, images are served by nginx, not the django server. I fixed the discord link and twitter account has been unsuspended.
